name: install-crowdin-cli

description: Install Crowdin CLI

inputs:
  crowdin-version:
    required: false
    description: 'Specific version of Crowdin to install.'
    default: ''


runs:
  using: composite
  steps:
    - name: Install Crowdin CLI
      shell: bash
      run: |
        npm install -g @crowdin/cli@${{ inputs.crowdin-version }}
        crowdin --version
