# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: get-crowdin-status-progress

description: Get the Crowdin Status Progress

inputs:
  crowdin-config-file:
    required: true
    description: xxx
  crowdin-branch-name:
    required: true
    description: xxx
  crowdin-personal-token:
    required: true
    description: xxx
    default: ''

outputs:
  CROWDIN_STATUS_PROGRESS:
    value: ${{ steps.gcsp.outputs.CROWDIN_STATUS_PROGRESS }}
    description: xxx

runs:
  using: composite
  steps:
    - name: Get the Crowdin Status Progress
      id: gcsp
      shell: bash
      run: |
        CROWDIN_BRANCH_NAME=${{ inputs.crowdin-branch-name }}
        CROWDIN_CONFIG_FILE=$(echo "${{ inputs.crowdin-config-file }}" | sed 's#\\#/#g' | sed 's#^\([A-Za-z]\):#/\L\1#')
        CROWDIN_PERSONAL_TOKEN=${{ inputs.crowdin-personal-token }}
        CROWDIN_STATUS_OUTPUT=$(crowdin status 
          --branch=${CROWDIN_BRANCH_NAME} 
          --config=${CROWDIN_CONFIG_FILE} 
          --token=${CROWDIN_PERSONAL_TOKEN}
          --no-progress --verbose 2>&1)
        CROWDIN_STATUS_PROGRESS=$(echo "${CROWDIN_STATUS_OUTPUT}" | sed '/Fetching project info/d' | sed 's/\t/  /g')
        DELIMITER="$(openssl rand -hex 8)"
        echo "CROWDIN_STATUS_PROGRESS<<${DELIMITER}"    >> ${GITHUB_OUTPUT}
        echo "${CROWDIN_STATUS_PROGRESS}"               >> ${GITHUB_OUTPUT}
        echo "${DELIMITER}"                             >> ${GITHUB_OUTPUT}
        echo "CROWDIN_STATUS_PROGRESS:"
        echo "${CROWDIN_STATUS_PROGRESS}"
