name: install-gettext

description: Install Gettext

inputs:
  gettext-version:
    required: false
    description: 'Specific version of Gettext to install.'
    default: ''


runs:
  using: composite
  steps:
    - name: Check if conda is installed
      shell: bash
      run: |
        which conda
        conda --version

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        activate-environment: ""

    - name: Install Gettext by Conda
      shell: bash
      run: |
        conda install gettext=${{ inputs.gettext-version }} --channel conda-forge

    - name: Check if gettext is installed (Windows)
      shell: cmd
      run: |
        where xgettext
        xgettext --version

    - name: Check if gettext is installed (Linux/macOS)
      shell: cmd
      run: |
        which xgettext
        xgettext --version
