name: install-gettext

description: Install Gettext

inputs:
  gettext-version:
    required: false
    description: 'Specific version of Gettext to install.'
    default: ''
  token:
    required: false
    description: xxx
    default: '${{ github.token }}'

runs:
  using: composite
  steps:
    # - uses: conda-incubator/setup-miniconda@v3
    #   with:
    #     auto-activate-base: true
    #     activate-environment: ""

    # - name: Check if conda is installed
    #   shell: bash
    #   run: |
    #     which conda
    #     conda --version

    # - name: Install Gettext by Conda
    #   shell: bash
    #   run: |
    #     conda install gettext=${{ inputs.gettext-version }} --channel conda-forge

    - name: Install winget
      if: ${{ runner.os == 'Windows' }}
      uses: Cyberboss/install-winget@v1
      with:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Install Gettext by Aptget (Ubuntu)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt install gettext

    - name: Install Gettext by Winget (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        winget install mlocati.GetText --accept-source-agreements --accept-package-agreements
        setx /M PATH "C:\Program Files\gettext-iconv\bin;%PATH%"
        set     PATH="C:\Program Files\gettext-iconv\bin;%PATH%"

    - name: Install Gettext by Homebrew (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew install gettext

    - name: Check if gettext is installed (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        where xgettext
        xgettext --version
        # "C:\Program Files\gettext-iconv\bin\xgettext.exe" --version

    - name: Check if gettext is installed (Linux/macOS)
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      shell: bash
      run: |
        which xgettext
        xgettext --version
