name: install-gettext

description: Install Gettext

inputs:
  gettext-version:
    required: false
    description: 'Specific version of Gettext to install.'
    default: ''


runs:
  using: composite
  steps:
    # - uses: conda-incubator/setup-miniconda@v3
    #   with:
    #     auto-activate-base: true
    #     activate-environment: ""

    # - name: Check if conda is installed
    #   shell: bash
    #   run: |
    #     which conda
    #     conda --version

    # - name: Install Gettext by Conda
    #   shell: bash
    #   run: |
    #     conda install gettext=${{ inputs.gettext-version }} --channel conda-forge

    - name: Install winget
      if: ${{ runner.os == 'Windows' }}
      uses: Cyberboss/install-winget@v1

    - name: Install Gettext by Aptget (Ubuntu)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt install gettext

    - name: Install Gettext by Winget (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        winget install mlocati.GetText

    - name: Install Gettext by Homebrew (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew install gettext

    - name: Check if gettext is installed (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        where xgettext
        xgettext --version

    - name: Check if gettext is installed (Linux/macOS)
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      shell: bash
      run: |
        which xgettext
        xgettext --version
