name: install-gettext

description: Install Gettext

inputs:
  token:
    required: false
    description: xxx
    default: '${{ github.token }}'

runs:
  using: composite
  steps:
    - name: Install Winget
      if: ${{ runner.os == 'Windows' }}
      uses: Cyberboss/install-winget@v1
      with:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Install Gettext by Aptget (Ubuntu)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt install gettext

    - name: Install Gettext by Homebrew (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew install gettext

    - name: Install Gettext by Winget (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        winget install mlocati.GetText --accept-source-agreements --accept-package-agreements
        echo "C:\Program Files\gettext-iconv\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Check if Gettext is installed (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        where xgettext
        xgettext --version

    - name: Check if Gettext is installed (Linux/macOS)
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      shell: bash
      run: |
        which xgettext
        xgettext --version
