# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: get-statistic-info-from-statistic

description: Get the Statistic Information from statistic.txt

inputs:
  version:
    required: true
    description: xxx
  workspace:
    required: false
    description: xxx
    default: '${{ github.workspace }}'

outputs:
  STATISTIC_INFO:
    value: ${{ steps.gsi.outputs.STATISTIC_INFO }}
    description: xxx

runs:
  using: composite
  steps:
    - name: Get the Statistic Information from statistic.txt
      id: gsi
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        WORKSPACE=$(echo "${{ inputs.workspace }}" | sed 's#\\#/#g' | sed 's#^\([A-Za-z]\):#/\L\1#')

        cd ${WORKSPACE}

        STATISTIC_TXT_PATH=l10n/${VERSION}/statistic.txt
        DELIMITER="$(openssl rand -hex 8)"
        echo "STATISTIC_INFO<<${DELIMITER}" >> ${GITHUB_OUTPUT}
        echo "$(<${STATISTIC_TXT_PATH})"    >> ${GITHUB_OUTPUT}
        echo "${DELIMITER}"                 >> ${GITHUB_OUTPUT}

        echo "STATISTIC_INFO:"
        echo "$(<${STATISTIC_TXT_PATH})"
