name: cmake-configure

description: Configure the project with CMake

inputs:
  source-directory:     # required
    required: false
    description: ''
    default: '${{ github.workspace }}'
  preset-name:          # required
    required: false
    description: ''
    default: 'all'
  cache-language:       # required
    required: false
    description: ''
    default: '[default]'
  cache-version:        # required
    required: false
    description: ''
    default: '[default]'
  cache-update-mode:    # required
    required: false
    description: ''
    default: 'ON'
  cache-install-mode:   # required
    required: false
    description: ''
    default: 'OFF'
  cache-auto-depend:
    required: false
    description: ''
    default: '[default]'
  cache-remove-redundant:
    required: false
    description: ''
    default: 'ON'
  cache-compend-version:
    required: false
    description: ''
    default: 'git-master'
  cache-exact-version-git:
    required: false
    description: ''
    default: '[default]'
  cache-exact-version-python:
    required: false
    description: ''
    default: '[default]'
  cache-exact-version-gettext:
    required: false
    description: ''
    default: '[default]'
  cache-exact-version-crowdin:
    required: false
    description: ''
    default: '[default]'
  cache-gettext-wrap-width:
    required: false
    description: ''
    default: '79'
  cache-gettext-additional-targets:
    required: false
    description: ''
    default: '[default]'
  cache-sphinx-builder:
    required: false
    description: ''
    default: 'html'
  cache-sphinx-console-locale:
    required: false
    description: ''
    default: '[default]'
  cache-sphinx-verbose-level:
    required: false
    description: ''
    default: '[default]'
  cache-sphinx-job-number:
    required: false
    description: ''
    default: '[default]'

runs:
  using: composite
  steps:
    # - name: Print All Inputs JSON
    #   shell: bash
    #   run: |
    #     echo '[Inputs]'
    #     echo '${{ toJSON(inputs) }}'
    #     echo '[GitHub]'
    #     echo '${{ toJSON(github) }}'

      - name: Install CMake 3.15
        uses: jwlawson/actions-setup-cmake@v2.0
        with:
          cmake-version: '3.15'

    - name: Configure with '${{ inputs.LANGUAGE }}' preset for '${{ inputs.VERSION }}' version
      shell: bash
      # run: |
      #   cmake \
      #     --preset ${{ inputs.LANGUAGE }} \
      #     -D VERSION=${{ inputs.VERSION }} \
      #     -D UPDATE_MODE=${{ inputs.UPDATE_MODE }} \
      #     -D AUTO_DEPEND=OFF
      # run: |
      #   # cmake_args=()
      #   for var in $(echo '${{ fromJSON(inputs) }}' | jq -r 'keys[]'); do
      #     echo "var: $var"
      #   done
      run: |
        # set -x
        inputs_compact=$(echo '${{ toJSON(inputs) }}' | jq -c)
        inputs_keys=$(echo "$inputs_compact" | jq -r 'keys[]')
        cmake_args=()
        for key in $inputs_keys; do
          value=$(echo "$inputs_compact" | jq -r --arg key "${key}" '.[$key]')
          cmake_arg=""
          if [[   "$key" == "source-directory" ]]; then
            cmake_arg="-S=${value}"
          elif [[ "$key" == "preset-name" ]]; then
            cmake_arg="--preset=${value}"
          elif [[ "$key" =~ ^cache- ]]; then
            if [ "$value" != "[default]" ]; then
              cmake_arg="-D$(echo "$key" | sed 's/^cache-\(.*\)/\U\1/' | sed 's/-/_/g')=${value}"
            fi
          else
            echo "key is other."
          fi
          # echo "cmake_arg: ${cmake_arg}"
          cmake_args+=($cmake_arg)
        done
        echo "Printing cmake_args:"
        for arg in "${cmake_args[@]}"; do
          echo "$arg"
        done
      # run: |
      #     delimiter="$(openssl rand -hex 8)"
      #     echo 'inputs_compact<<$delimiter'     >> $GITHUB_ENV
      #     echo '${{ toJSON(inputs) }}' | jq -c  >> $GITHUB_ENV
      #     echo '$delimiter'                     >> $GITHUB_ENV
      #     echo 'inpus_compact:'
      #     echo '${{ env.inpus_compact }}'
      # run: |
      #   echo '${{ toJSON(inputs) }}' | jq -c
      #   # # Run cmake with constructed arguments
      #   # echo "cmake ${cmake_args[@]}"
      # run: |
      #   echo '${{ toJSON(inputs) }}' | jq -c
