# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: ci-deploy-po-version

on:
  schedule:
    - cron: '0 8  1 * *'  # Runs at 08:00 on day  1 of the month in UTC zone
    - cron: '0 8 15 * *'  # Runs at 08:00 on day 15 of the month in UTC zone
  workflow_dispatch:
    inputs:
      TYPE:
        description: 'Set TYPE input'
        required: true
        type: choice
        default: 'matrix'
        options:
          - 'matrix'
          - 'single'
      VERSION:
        description: 'Set VERSION input (for single type)'
        required: true
        type: string
        default: 'git-master'

jobs:
  get-matrix:
    if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' ) ||
        ( github.event_name == 'schedule' )
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.rvm.outputs.VERSION }}
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Read VERSION from matrix.json
        id: rvm
        run: |
          FILTER=".include | map(.VERSION)"
          VERSION=$(jq -c "$FILTER" .github/workflows/matrix.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION:"
          echo "$VERSION" | jq "."

  matrix:
    needs: get-matrix
    if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' ) ||
        ( github.event_name == 'schedule' )
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.VERSION }}
      cancel-in-progress: true
    strategy:
      matrix: 
        VERSION: ${{ fromJSON(needs.get-matrix.outputs.VERSION) }}
      fail-fast: false
    uses: ./.github/workflows/use-deploy-po-version.yml
    with:
      RUNNER: 'ubuntu-latest'
      CHECKOUT: ${{ github.ref }}
      VERSION: ${{ matrix.VERSION }}
      CALLER_JOB: 'matrix (${{ matrix.VERSION }})'
      ENABLE_JOB: true

  single:
    if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'single' )
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.VERSION }}
      cancel-in-progress: true
    uses: ./.github/workflows/use-deploy-po-version.yml
    with:
      RUNNER: 'ubuntu-latest'
      CHECKOUT: ${{ github.ref }}
      VERSION: ${{ inputs.VERSION }}
      CALLER_JOB: 'single'
      ENABLE_JOB: true
