# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: ci-deploy-po-version

on:
  schedule:
    - cron: '0 8 1,15 * *'  # Runs at 08:00 on day 1 and 15 of the month in UTC zone
  workflow_dispatch:
    inputs:
      TYPE:
        description: 'TYPE input'
        required: true
        type: choice
        default: 'matrix'
        options:
          - 'matrix'
          - 'single'
      VERSION:
        description: 'VERSION input (for single type)'
        required: true
        type: string
        default: 'git-master'
      VERSION_GROUP:
        description: 'VERSION_GROUP input (for matrix type)'
        required: true
        type: choice
        default: 'include'
        options:
          - 'v3'

env:
  CRON_V3: '0 8 1,15 * *'

jobs:
  get-matrix:
    if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' ) ||
        ( github.event_name == 'schedule' )
    runs-on: ubuntu-latest
    outputs:
      VERSION_LIST: ${{ steps.gvl.outputs.VERSION_LIST }}
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Get VERSION_GROUP from Inputs or Schedule
        id: gvg
        shell: bash
        run: |
          INPUTS_VERSION_GROUP="${{ inputs.VERSION_GROUP }}"
          GITHUB_EVENT_NAME="${{ github.event_name }}"
          GITHUB_EVENT_SCHEDULE="${{ github.event.schedule }}"
          if [[ ${GITHUB_EVENT_NAME} == "workflow_dispatch" ]]; then
            VERSION_GROUP="${INPUTS_VERSION_GROUP}"
          elif [[ ${GITHUB_EVENT_NAME} == "schedule" ]]; then
            if [[ ${GITHUB_EVENT_SCHEDULE} == "${{ env.CRON_V3 }}" ]]; then
              VERSION_GROUP="v3"
            fi
          fi
          echo "VERSION_GROUP=${VERSION_GROUP}" >> ${GITHUB_OUTPUT}
      - name: Get VERSION_LIST from versions.json
        id: gvl
        shell: bash
        run: |
          VERSION_GROUP=${{ steps.gvg.outputs.VERSION_GROUP }}
          JQ_FILE="versions.json"
          JQ_FILTER=".${VERSION_GROUP} | map(.VERSION)"
          VERSION_LIST=$(jq -c "${JQ_FILTER}" "${JQ_FILE}")
          echo "VERSION_LIST=${VERSION_LIST}" >> ${GITHUB_OUTPUT}
          echo "VERSION_LIST:"
          echo "${VERSION_LIST}" | jq "."

  matrix:
    needs: get-matrix
    if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' ) ||
        ( github.event_name == 'schedule' )
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.VERSION }}
      cancel-in-progress: true
    strategy:
      matrix: 
        VERSION: ${{ fromJSON(needs.get-matrix.outputs.VERSION_LIST) }}
      fail-fast: false
    uses: ./.github/workflows/use-deploy-po-version.yml
    with:
      ACTOR: 'ltdrobot'
      RUNNER: 'ubuntu-latest'
      CHECKOUT: ${{ github.ref }}
      VERSION: ${{ matrix.VERSION }}
      CALLER_JOB: 'matrix (${{ matrix.VERSION }})'
      ENABLE_JOB: true

  single:
    if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'single' )
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.VERSION }}
      cancel-in-progress: true
    uses: ./.github/workflows/use-deploy-po-version.yml
    with:
      ACTOR: 'ltdrobot'
      RUNNER: 'ubuntu-latest'
      CHECKOUT: ${{ github.ref }}
      VERSION: ${{ inputs.VERSION }}
      CALLER_JOB: 'single'
      ENABLE_JOB: true
