# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: ci-gettext-statistic-po

on:
  schedule:
    - cron: '0 0 1,15 * *'  # Runs at 00:00 on day 1 and 15 of the month in UTC zone
  workflow_dispatch:
    inputs:
      TYPE:
        description: 'Set TYPE input'
        required: true
        type: choice
        default: 'matrix'
        options:
          - 'matrix'
          - 'single'
      VERSION:
        description: 'Set VERSION input (for single type)'
        required: true
        type: string
        default: 'git-master'
      MATRIX_GROUP:
        description: 'Set MATRIX_GROUP input (for single type)'
        required: true
        type: string
        default: 'include'

jobs:
  get-matrix:
    if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' ) ||
        ( github.event_name == 'schedule' )
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.rvm.outputs.VERSION }}
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Read VERSION from matrix.json
        id: rvm
        run: |
          MATRIX=".github/workflows/matrix.json"
          FILTER=".include | map(.VERSION)"
          VERSION=$(jq -c "${FILTER}" ${MATRIX})
          echo "VERSION=${VERSION}" >> ${GITHUB_OUTPUT}
          echo "VERSION:"
          echo "${VERSION}" | jq "."

  matrix:
    needs: get-matrix
    if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'matrix' ) ||
        ( github.event_name == 'schedule' )
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.VERSION }}
      cancel-in-progress: true
    strategy:
      matrix: 
        VERSION: ${{ fromJSON(needs.get-matrix.outputs.VERSION) }}
      fail-fast: false
    uses: ./.github/workflows/use-gettext-statistic-po.yml
    with:
      RUNNER: 'ubuntu-latest'
      CHECKOUT: ${{ github.ref }}
      VERSION: ${{ matrix.VERSION }}
      CALLER_JOB: 'matrix (${{ matrix.VERSION }})'
      ENABLE_JOB: true
      MATRIX_GROUP: 'include'

  single:
    if: ( github.event_name == 'workflow_dispatch' && inputs.TYPE == 'single' )
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.VERSION }}
      cancel-in-progress: true
    uses: ./.github/workflows/use-gettext-statistic-po.yml
    with:
      RUNNER: 'ubuntu-latest'
      CHECKOUT: ${{ github.ref }}
      VERSION: ${{ inputs.VERSION }}
      CALLER_JOB: 'single'
      ENABLE_JOB: true
      MATRIX_GROUP: ${{ inputs.MATRIX_GROUP }}
