# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: ci-update-submodules

on:
  schedule:
    - cron: '0 0 1,15 * *'  # Runs at 08:00 on day 1 and 15 of the month in UTC zone
  workflow_dispatch:

jobs:
  get-submodules:
    runs-on: ubuntu-latest
    outputs:
      SUBMODULE_LIST: ${{ steps.get-submodules.outputs.SUBMODULE_LIST }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Get submodule directories
        id: get-submodules
        shell: bash
        run: |
          SUBMODULE_PATHS=$(git config --file .gitmodules --get-regexp path | awk '{print $2}')
          SUBMODULE_LIST=$(echo "${SUBMODULE_PATHS}" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "SUBMODULE_LIST=${SUBMODULE_LIST}" >> ${GITHUB_OUTPUT}
          echo "SUBMODULE_LIST:"
          echo "${SUBMODULE_LIST}" | jq "."

  update-submodules:
    needs: get-submodules
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        SUBMODULE_DIR: ${{ fromJSON(needs.get-submodules.outputs.SUBMODULE_LIST) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Print submodule directory
        run: |
          echo "Processing submodule directory: ${{ matrix.SUBMODULE_DIR }}"

      - name: Set old commit hash
        shell: bash
        run: |
          git submodule status -- ${{ matrix.SUBMODULE_DIR }} | awk '{print $1}'
          git submodule status -- ${{ matrix.SUBMODULE_DIR }} | awk '{print $1}' | sed 's/[^a-f0-9]//g'

      - name: Update submodule from remote
        shell: bash
        run: |
          git submodule update --init --remote ${{ matrix.SUBMODULE_DIR }}

      - name: Set new commit hash 1
        shell: bash
        run: |
          git submodule status -- ${{ matrix.SUBMODULE_DIR }} | awk '{print $1}'
          git submodule status -- ${{ matrix.SUBMODULE_DIR }} | awk '{print $1}' | sed 's/[^a-f0-9]//g'

      - name: Set new commit hash 2
        run: |
          git rev-parse HEAD:cmake/modules

      # - name: Add and Commit Changes
      #   id: acc
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     cwd: '.'
      #     add: '.'
      #     pull: '--rebase --autostash'
      #     author_name: docs-l10n[bot]
      #     author_email: 157310748+docs-l10n[bot]@users.noreply.github.com
      #     message: |

