# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: ci-update-submodules

on:
  schedule:
    - cron: '0 0 1,15 * *'  # Runs at 08:00 on day 1 and 15 of the month in UTC zone
  workflow_dispatch:

jobs:
  get-matrix:
    if: ( github.event_name == 'schedule' ) ||
        ( github.event_name == 'workflow_dispatch' )
    runs-on: 'ubuntu-latest'
    outputs:
      SUBMODULE_LIST: ${{ steps.gsl.outputs.SUBMODULE_LIST }}
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: false
      - name: Get Submodule List
        id: gsl
        shell: bash
        run: |
          SUBMODULE_LINES=$(git config --file .gitmodules --get-regexp path | awk '{print $2}')
          SUBMODULE_LIST=$(echo "${SUBMODULE_LINES}" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "SUBMODULE_LIST=${SUBMODULE_LIST}" >> ${GITHUB_OUTPUT}
          echo "SUBMODULE_LIST:"
          echo "${SUBMODULE_LIST}" | jq "."

  matrix:
    needs: get-matrix
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.SUBMODULE }}
      cancel-in-progress: true
    strategy:
      matrix: 
        SUBMODULE: ${{ fromJSON(needs.get-matrix.outputs.SUBMODULE_LIST) }}
      fail-fast: false
    uses: ./.github/workflows/use-update-submodules.yml
    with:
      RUNNER: 'ubuntu-latest'
      CHECKOUT: ${{ github.ref }}
      SUBMODULE: ${{ matrix.SUBMODULE }}
      CALLER_JOB: 'matrix (${{ matrix.SUBMODULE }})'
      ENABLE_JOB: true
