# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: tests

on:
  push:
    branches: 
      - 'source'
    paths:
      - '.github/actions/cmake-configure/action.yml'
  workflow_dispatch:

jobs:
  single:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Check whether Conda is installed
        run: |
          which conda

      - name: Configure the project with CMake
        uses: ./.github/actions/cmake-configure

      - name: Check whether Conda is installed
        run: |
          which conda
