# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: tests

on:
  push:
    branches: 
      - 'source'
    paths:
      - '.github/actions/cmake-configure/action.yml'
  workflow_dispatch:

jobs:
  single:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'windows-latest'
          - 'ubuntu-latest'
          - 'macos-latest'
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Setup CMake 3.23
        uses: jwlawson/actions-setup-cmake@v2.0
        with:
          cmake-version: '3.23'

      # - name: Check whether CMake is installed
      #   run: |
      #     which cmake && cmake --version

      - name: Configure the project with CMake
        uses: ./.github/actions/cmake-configure
        with:
          source-directory: '${{ github.workspace }}'
          language: 'all'
          version: 'git-master'

      # - name: Check whether CMake is installed
      #   run: |
      #     which cmake && cmake --version

      - name: Check whether Node.js is installed (for Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: cmd
        run: |
          where node && node --version

      - name: Check whether Node.js is installed (for Linux/macOS)
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        shell: bash
        run: |
          which node && node --version
