# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: tests

on:
  # push:
  #   branches: 
  #     - 'source'
  #   paths:
  #     - '.github/actions/cmake-configure/action.yml'
  #     - '.github/workflows/tests.yml'
  workflow_dispatch:
    inputs:
      LANGUAGE:
        type: string
        default: 'all'
        description: xxx
        required: true
      VERSION:
        type: string
        default: 'git-master'
        description: yyy
        required: true

jobs:
  single:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'windows-latest'
          - 'ubuntu-latest'
          - 'macos-latest'
      fail-fast: false
    steps:
      - name: Check Contexts, Inputs, and Secrets
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "[Inputs]"
          echo "inputs.CHECKOUT = ${{ inputs.CHECKOUT }}"
          echo "inputs.VERSION = ${{ inputs.VERSION }}"
          echo "inputs.LANGUAGE = ${{ inputs.LANGUAGE }}"
          echo "inputs.UPDATE_MODE = ${{ inputs.UPDATE_MODE }}"
          echo "inputs.CALLER_JOB = ${{ inputs.CALLER_JOB }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "[Secrets]"
          echo "secrets.APP_ID = ${{ secrets.APP_ID }}"
          echo "secrets.APP_PRIVATE_KEY = ${{ secrets.APP_PRIVATE_KEY }}"
          echo "secrets.GH_PERSONAL_TOKEN = ${{ secrets.GH_PERSONAL_TOKEN }}"
          echo "secrets.CROWDIN_PERSONAL_TOKEN = ${{ secrets.CROWDIN_PERSONAL_TOKEN }}"

      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Install CMake
        uses: ./.github/actions/install-cmake
        with:
          cmake-version: '3.23'

      - name: Install Crowdin CLI
        uses: ./.github/actions/install-crowdin-cli
        with:
          crowdin-version: '4'

      - name: Set Environment Variables to $GITHUB_ENV
        shell: bash
        run: |
          echo "CROWDIN_PERSONAL_TOKEN=${{ secrets.CROWDIN_PERSONAL_TOKEN }}" >> $GITHUB_ENV

      - name: Set CROWDIN_LANGUAGE_ARGS to $GITHUB_OUTPUT
        id: slago
        uses: ./.github/actions/set-crowdin-language-args
        with:
          language: 'all'

      - name: Crowdin Download Documents from the '${{ inputs.VERSION }}' Branch
        shell: bash
        run: |
          crowdin download \
            --dryrun \
            ${{ steps.slago.outputs.CROWDIN_LANGUAGE_ARGS }} \
            --branch ${{ inputs.VERSION }} \
            --export-only-approved \
            --no-progress \
            --verbose

      - name: Get the Translated/Proofread Progress
        id: gtpp
        shell: bash
        run: |
          CROWDIN_YML_PATH=$(pwd)/crowdin.yml
          CROWDIN_STATUS_OUTPUT=$(crowdin status --branch=repo --config=$CROWDIN_YML_PATH --no-progress --verbose 2>&1)
          PROGRESS_OUTPUT=$(echo "$CROWDIN_STATUS_OUTPUT" | sed '/Fetching project info/d' | sed 's/\t/  /g')
          delimiter="$(openssl rand -hex 8)"
          echo "PROGRESS_OUTPUT<<$delimiter"  >> $GITHUB_OUTPUT
          echo "$PROGRESS_OUTPUT"             >> $GITHUB_OUTPUT
          echo "$delimiter"                   >> $GITHUB_OUTPUT
          echo "PROGRESS_OUTPUT:"
          echo "$PROGRESS_OUTPUT"

      # # - name: Check whether CMake is installed
      # #   run: |
      # #     which cmake && cmake --version

      # - name: Configure the project
      #   uses: ./.github/actions/cmake-configure
      #   with:
      #     source-directory: '${{ github.workspace }}'
      #     language: 'all'
      #     version: 'git-master'

      # - name: Build the 'prepare_repositories' target
      #   uses: ./.github/actions/cmake-build
      #   with:
      #     source-directory: '${{ github.workspace }}'
      #     language: 'all'
      #     target: 'prepare_repositories'

      # # - name: Check whether CMake is installed
      # #   run: |
      # #     which cmake && cmake --version

      # - name: Check whether Node.js is installed (for Windows)
      #   if: ${{ runner.os == 'Windows' }}
      #   shell: cmd
      #   run: |
      #     where node && node --version

      # - name: Check whether Node.js is installed (for Linux/macOS)
      #   if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      #   shell: bash
      #   run: |
      #     which node && node --version
