# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-update-submodules

on:
  workflow_call:
    inputs:
      RUNNER:
        type: string
        required: true
      CHECKOUT:
        type: string
        required: true
      CALLER_JOB:
        type: string
        required: true
      ENABLE_JOB:
        type: boolean
        required: true

jobs:
  get-submodules:
    if: inputs.ENABLE_JOB
    runs-on: ${{ inputs.RUNNER }}
    outputs:
      SUBMODULE_LIST: ${{ steps.get-submodules.outputs.SUBMODULE_LIST }}
    steps:
      - name: Checkout to '${{ inputs.CHECKOUT }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT }}
          submodules: false

      - name: Get submodule directories
        id: get-submodules
        shell: bash
        run: |
          SUBMODULE_PATHS=$(git config --file .gitmodules --get-regexp path | awk '{print $2}')
          SUBMODULE_LIST=$(echo "${SUBMODULE_PATHS}" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "SUBMODULE_LIST=${SUBMODULE_LIST}" >> ${GITHUB_OUTPUT}
          echo "SUBMODULE_LIST:"
          echo "${SUBMODULE_LIST}" | jq "."

  update-submodules:
    needs: get-submodules
    runs-on: ${{ inputs.RUNNER }}
    strategy:
      matrix: 
        SUBMODULE_DIR: ${{ fromJSON(needs.get-submodules.outputs.SUBMODULE_LIST) }}
      fail-fast: false
    steps:
      - name: Check Contexts, Inputs, and Secrets
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.run_id = ${{ github.run_id }}"
          echo "[Inputs]"
          echo "inputs.RUNNER = ${{ inputs.RUNNER }}"
          echo "inputs.CHECKOUT = ${{ inputs.CHECKOUT }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "[Secrets]"

      - name: Checkout to '${{ inputs.CHECKOUT }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT }}
          submodules: false

      - name: Get Old Commit of the Submodule '${{ matrix.SUBMODULE_DIR }}'
        id: gocs
        shell: bash
        run: |
          OLD_COMMIT=$(git submodule status -- ${{ matrix.SUBMODULE_DIR }} | awk '{print $1}' | sed 's/[^a-f0-9]//g')
          echo "OLD_COMMIT=${OLD_COMMIT}" >> ${GITHUB_OUTPUT}
          echo "OLD_COMMIT: ${OLD_COMMIT}"

      - name: Update submodule from remote
        shell: bash
        run: |
          git submodule update --init --remote ${{ matrix.SUBMODULE_DIR }}

      - name: Get New Commit of the Submodule '${{ matrix.SUBMODULE_DIR }}'
        id: gncs
        shell: bash
        run: |
          NEW_COMMIT=$(git submodule status -- ${{ matrix.SUBMODULE_DIR }} | awk '{print $1}' | sed 's/[^a-f0-9]//g')
          echo "NEW_COMMIT=${NEW_COMMIT}" >> ${GITHUB_OUTPUT}
          echo "NEW_COMMIT: ${NEW_COMMIT}"

      - name: Get Repository Url of the Submodule '${{ matrix.SUBMODULE_DIR }}'
        id: grus
        shell: bash
        run: |
          REPO_URL=$(git config --get submodule.${{ matrix.SUBMODULE_DIR }}.url)
          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_OUTPUT}
          echo "REPO_URL: ${REPO_URL}"

      - name: Compare Commits of Old and New
        id: ccon
        run: |
          if [ "${{ steps.gocs.outputs.OLD_COMMIT }}" != "${{ steps.gncs.outputs.NEW_COMMIT }}" ]; then
            COMMITS_ARE_DIFFERENT=true
          else
            COMMITS_ARE_DIFFERENT=false
          fi
          echo "COMMITS_ARE_DIFFERENT=${COMMITS_ARE_DIFFERENT}" >> ${GITHUB_OUTPUT}
          echo "COMMITS_ARE_DIFFERENT: ${COMMITS_ARE_DIFFERENT}"

      - name: Get the Current Job's ID
        id: gcji
        uses: Tiryoh/gha-jobid-action@v1
        with:
          github_token: ${{ steps.ggat.outputs.token }}
          job_name: '${{ inputs.CALLER_JOB }} / ${{ github.job }}'
          per_page: 100

      - name: Add and Commit Changes
        id: acc
        if: ${{ steps.ccon.outputs.COMMITS_ARE_DIFFERENT == 'true' }}
        uses: EndBug/add-and-commit@v9
        with:
          cwd: '.'
          add: '.'
          pull: '--rebase --autostash'
          author_name: docs-l10n[bot]
          author_email: 157310748+docs-l10n[bot]@users.noreply.github.com
          # author_name: ltdrobot
          # author_email: 178366084+ltdrobot@users.noreply.github.com
          message: |
            feat: update '${{ matrix.SUBMODULE_DIR }}' submodule

            Updated '${{ matrix.SUBMODULE_DIR }}' submodule to include the latest changes.

            - Repository: ${{ steps.grus.outputs.REPO_URL }}
            - Old commit: ${{ steps.gocs.outputs.OLD_COMMIT }}
            - New commit: ${{ steps.gncs.outputs.NEW_COMMIT }}

            Created by GitHub Workflows:

            - File: ${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ github.workflow }}.yml
            - Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.gcji.outputs.job_id }}

      - name: Check Outputs of the Commit
        if: steps.acc.outputs.committed == 'true'
        shell: bash
        run: |
          echo "Commit's SHA = ${{ steps.acc.outputs.commit_long_sha }}"
          echo "Commit's URL = ${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.acc.outputs.commit_long_sha }}"
