# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-crowdin-document

on:
  workflow_call:
    inputs:
      RUNNER:           # required
        type: string
        required: true
      CHECKOUT:         # required
        type: string
        required: true
      VERSION:          # required
        type: string
        required: true
      LANGUAGE:         # required
        type: string
        required: true
      CALLER_JOB:       # required
        type: string
        required: true
      ENABLE_JOB:       # required
        type: boolean
        required: true

jobs:
  crowdin-document:
    if: inputs.ENABLE_JOB
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Check Contexts, Inputs, and Secrets
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "[Inputs]"
          echo "inputs.RUNNER = ${{ inputs.RUNNER }}"
          echo "inputs.CHECKOUT = ${{ inputs.CHECKOUT }}"
          echo "inputs.VERSION = ${{ inputs.VERSION }}"
          echo "inputs.LANGUAGE = ${{ inputs.LANGUAGE }}"
          echo "inputs.CALLER_JOB = ${{ inputs.CALLER_JOB }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "[Secrets]"
          echo "secrets.APP_ID = ${{ secrets.APP_ID }}"
          echo "secrets.APP_PRIVATE_KEY = ${{ secrets.APP_PRIVATE_KEY }}"
          echo "secrets.CROWDIN_PERSONAL_TOKEN = ${{ secrets.CROWDIN_PERSONAL_TOKEN }}"

      - name: Get the GitHub App's Token
        uses: tibdex/github-app-token@v2
        id: ggat
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout to '${{ inputs.CHECKOUT }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT }}
          token: ${{ steps.ggat.outputs.token }}
          fetch-depth: 0

      # - name: Set up Environment Variables
      #   shell: bash
      #   run: |
      #     echo "CROWDIN_PERSONAL_TOKEN=${{ secrets.CROWDIN_PERSONAL_TOKEN }}" >> ${GITHUB_ENV}

      - name: Install Crowdin
        uses: ./.github/actions/install-crowdin

      - name: Get the Crowdin Language List
        id: gcll
        uses: ./.github/actions/get-crowdin-language-list
        with:
          language: ${{ inputs.LANGUAGE }}

      - name: Upload Sources of the '${{ inputs.VERSION }}' branch to Crowdin
        continue-on-error: true
        uses: ./.github/actions/crowdin-upload-sources
        with:
          crowdin-config-file: 'crowdin.yml'
          crowdin-branch-name: 'repo'
          crowdin-personal-token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          crowdin-no-progress: 'true'
          crowdin-verbose: 'true'

      #
      # If the '${{ inputs.VERSION }}' is not 'repo', then it will:
      # Delete the '${{ inputs.VERSION }}' branch in Crowdin.
      #

      - name: Delete the '${{ inputs.VERSION }}' branch in Crowdin
        if: inputs.VERSION != 'repo'
        uses: ./.github/actions/crowdin-branch-delete
        with:
          crowdin-config-file: 'crowdin.yml'
          crowdin-branch-name: ${{ inputs.VERSION }}
          crowdin-personal-token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      #
      # If the '${{ inputs.VERSION }}' is not 'repo', then it will:
      # 1. Download Translations of the '${{ inputs.VERSION }}' branch from Crowdin.
      # 2. Get the Translated/Proofread Progress.
      # 3. Get the Current Job's ID.
      # 4. Add and Commit the Changes.
      #

      - name: Download Translations of the '${{ inputs.VERSION }}' branch from Crowdin
        if: inputs.VERSION == 'repo'
        uses: ./.github/actions/crowdin-download-translations
        with:
          crowdin-config-file: 'crowdin.yml'
          crowdin-branch-name: ${{ inputs.VERSION }}
          crowdin-personal-token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          crowdin-language-list: ${{ steps.gcll.outputs.CROWDIN_LANGUAGE_LIST }}
          crowdin-export-only-approved: 'true'
          crowdin-no-progress: 'true'
          crowdin-verbose: 'true'

      - name: Get the Translated/Proofread Progress of the '${{ inputs.VERSION }}' branch from Crowdin
        id: gtpp
        if: inputs.VERSION == 'repo'
        uses: ./.github/actions/get-crowdin-status-progress
        with:
          crowdin-config-file: 'crowdin.yml'
          crowdin-branch-name: ${{ inputs.VERSION }}
          crowdin-personal-token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          crowdin-no-progress: 'true'
          crowdin-verbose: 'true'

      - name: Get the Current Job's ID
        id: gcji
        if: inputs.VERSION == 'repo'
        uses: Tiryoh/gha-jobid-action@v1
        with:
          github_token: ${{ steps.ggat.outputs.token }}
          job_name: '${{ inputs.CALLER_JOB }} / ${{ github.job }}'
          per_page: 100

      - name: Set up mutex for the '${{ github.ref_name }}' branch
        uses: ben-z/gh-action-mutex@v1.0.0-alpha.9
        with:
          branch: 'mutex/${{ github.ref_name }}'
          repo-token: ${{ steps.ggat.outputs.token }}

      - name: Add and Commit Changes
        id: acc
        uses: EndBug/add-and-commit@v9
        with:
          cwd: '.'
          add: '.'
          pull: '--rebase --autostash'
          author_name: docs-l10n[bot]
          author_email: 157310748+docs-l10n[bot]@users.noreply.github.com
          message: |
            tr(repo): Download Document Translations from Crowdin

            ${{ steps.gtpp.outputs.CROWDIN_STATUS_PROGRESS }}

            Created by GitHub Workflows:
            - File: ${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ github.workflow }}.yml
            - Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.gcji.outputs.job_id }}

      - name: Check Outputs of the Commit
        if: steps.acc.outputs.committed == 'true'
        shell: bash
        run: |
          echo "Commit's SHA = ${{ steps.acc.outputs.commit_long_sha }}"
          echo "Commit's URL = ${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.acc.outputs.commit_long_sha }}"
