# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-deploy-po-version

on:
  workflow_call:
    inputs:
      CHECKOUT:
        type: string
        required: true
      VERSION:
        type: string
        required: true
      CALLER_JOB:
        type: string
        required: true
      ENABLE_JOB:
        type: boolean
        required: true

jobs:
  deploy-po-version:
    #  Don't run on forked repos.
    if: inputs.ENABLE_JOB && github.repository_owner == 'hwhsu1231'
    runs-on: ubuntu-latest
    steps:
      - name: Check Contexts, Inputs, and Secrets
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.repository.default_branch = ${{ github.event.repository.default_branch }}"
          echo "[Inputs]"
          echo "inputs.CHECKOUT = ${{ inputs.CHECKOUT }}"
          echo "inputs.VERSION = ${{ inputs.VERSION }}"
          echo "inputs.CALLER_JOB = ${{ inputs.CALLER_JOB }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "[Secrets]"
          echo "secrets.APP_ID = ${{ secrets.APP_ID }}"
          echo "secrets.APP_PRIVATE_KEY = ${{ secrets.APP_PRIVATE_KEY }}"

      - name: Get the GitHub App's Token
        uses: tibdex/github-app-token@v2
        id: ggat
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout to '${{ inputs.CHECKOUT }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT }}
          token: ${{ steps.ggat.outputs.token }}
          submodules: true

      - name: Configure with 'all' preset for '${{ inputs.VERSION }}' version
        shell: bash
        run: |
          cmake \
            --preset all \
            -D VERSION=${{ inputs.VERSION }}

      - name: Build with 'readthedocs_symlinks' target
        shell: bash
        run: |
          cmake \
            --build out/build/all \
            --target readthedocs_symlinks

      - name: Remove 'l10n/${{ inputs.VERSION }}/locale/pot' directory
        run: |
          cd ${{ github.workspace }}
          cmake -E rm -rf l10n/${{ inputs.VERSION }}/locale/pot

      - name: Deploy to 'po/${{ inputs.VERSION }}' branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ steps.ggat.outputs.token }}
          branch: po/${{ inputs.VERSION }}
          folder: ./l10n/${{ inputs.VERSION }}/locale
          single-commit: true
          target-folder: .
          clean: true
