# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-gettext-update-po

on:
  workflow_call:
    inputs:
      RUNNER:
        type: string
        required: true
      CHECKOUT:
        type: string
        required: true
      VERSION:
        type: string
        required: true
      LANGUAGE:
        type: string
        required: true
      UPDATE_MODE:
        type: string
        required: true
      CALLER_JOB:
        type: string
        required: true
      ENABLE_JOB:
        type: boolean
        required: true

jobs:
  gettext-update-po:
    if: inputs.ENABLE_JOB
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Check Contexts, Inputs, and Secrets
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "[Inputs]"
          echo "inputs.RUNNER = ${{ inputs.RUNNER }}"
          echo "inputs.CHECKOUT = ${{ inputs.CHECKOUT }}"
          echo "inputs.VERSION = ${{ inputs.VERSION }}"
          echo "inputs.LANGUAGE = ${{ inputs.LANGUAGE }}"
          echo "inputs.UPDATE_MODE = ${{ inputs.UPDATE_MODE }}"
          echo "inputs.CALLER_JOB = ${{ inputs.CALLER_JOB }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "[Secrets]"
          echo "secrets.APP_ID = ${{ secrets.APP_ID }}"
          echo "secrets.APP_PRIVATE_KEY = ${{ secrets.APP_PRIVATE_KEY }}"

      - name: Get the GitHub App's Token
        id: ggat
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout to '${{ inputs.CHECKOUT }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT }}
          token: ${{ steps.ggat.outputs.token }}
          submodules: true
          fetch-depth: 0

      - name: Get Other Fields from matrix.json
        id: gofm
        shell: bash
        run: |
          get_keys() {
            jq -r ".include[0] | keys[] | select(. != \"VERSION\")" .github/workflows/matrix.json
          }
          declare -A VERSION_FILTERS
          for KEY in $(get_keys); do
            VERSION_FILTERS[$KEY]=".include[] | select(.VERSION == \"${{ inputs.VERSION }}\") | .$KEY"
          done
          for KEY in "${!VERSION_FILTERS[@]}"; do
            FILTER="${VERSION_FILTERS[$KEY]}"
            VALUE=$(jq -r "${FILTER}" .github/workflows/matrix.json)
            if [ "$VALUE" = "null" ]; then VALUE=""; fi
            echo "${KEY}=$VALUE" >> ${GITHUB_OUTPUT}
            echo "${KEY}: $VALUE"
          done

      - name: Install CMake 3.23
        uses: ./.github/actions/install-cmake
        with:
          cmake-version: '3.23'

      - name: Install Gettext
        uses: ./.github/actions/install-gettext

      - name: Configure with '${{ inputs.LANGUAGE }}' preset for '${{ inputs.VERSION }}' version
        uses: ./.github/actions/cmake-configure-preset
        with:
          source-directory: ${{ github.workspace }}
          preset: ${{ inputs.LANGUAGE }}
          cache-version: ${{ inputs.VERSION }}
          cache-update-mode: ${{ inputs.UPDATE_MODE }}
          cache-auto-depend: 'OFF'
          cache-version-exact-git: ${{ steps.gofm.outputs.VERSION_EXACT_GIT }}
          cache-version-exact-conda: ${{ steps.gofm.outputs.VERSION_EXACT_CONDA }}
          cache-version-exact-python: ${{ steps.gofm.outputs.VERSION_EXACT_PYTHON }}
          cache-version-exact-gettext: ${{ steps.gofm.outputs.VERSION_EXACT_GETTEXT }}
      # - name: Configure with '${{ inputs.LANGUAGE }}' preset for '${{ inputs.VERSION }}' version
      #   shell: bash
      #   run: |
      #     cmake \
      #       --preset ${{ inputs.LANGUAGE }} \
      #       -D VERSION=${{ inputs.VERSION }} \
      #       -D UPDATE_MODE=${{ inputs.UPDATE_MODE }} \
      #       -D AUTO_DEPEND=OFF

      - name: Get the Version Information of '.po' Before Building
        id: po-before
        uses: ./.github/actions/get-version-info-from-reference
        with:
          jq-filter: '.po'
          jq-file: '${{ github.workspace }}/l10n/${{ inputs.VERSION }}/reference.json'
      # - name: Get PO_BEFORE from reference.json
      #   id: po-before
      #   shell: bash
      #   run: |
      #     PO_BEFORE=$(jq ".po" l10n/${{ inputs.VERSION }}/reference.json)
      #     delimiter="$(openssl rand -hex 8)"
      #     echo "PO_BEFORE<<$delimiter"  >> ${GITHUB_OUTPUT}
      #     echo "$PO_BEFORE"             >> ${GITHUB_OUTPUT}
      #     echo "$delimiter"             >> ${GITHUB_OUTPUT}
      #     echo "PO_BEFORE:"
      #     echo "$PO_BEFORE"

      - name: Build the 'gettext_update_po' target
        uses: ./.github/actions/cmake-build-target
        with:
          source-directory: ${{ github.workspace }}
          preset: ${{ inputs.LANGUAGE }}
          target: 'gettext_update_po'

      - name: Get the Version Information of '.po' After Building
        id: po-after
        uses: ./.github/actions/get-version-info-from-reference
        with:
          jq-filter: '.po'
          jq-file: '${{ github.workspace }}/l10n/${{ inputs.VERSION }}/reference.json'
      # - name: Get PO_AFTER from reference.json
      #   id: po-after
      #   shell: bash
      #   run: |
      #     PO_AFTER=$(jq '.po' l10n/${{ inputs.VERSION }}/reference.json)
      #     delimiter="$(openssl rand -hex 8)"
      #     echo "PO_AFTER<<$delimiter" >> ${GITHUB_OUTPUT}
      #     echo "$PO_AFTER"            >> ${GITHUB_OUTPUT}
      #     echo "$delimiter"           >> ${GITHUB_OUTPUT}
      #     echo "PO_AFTER:"
      #     echo "$PO_AFTER"

      - name: Get the Current Job's ID
        id: gcji
        uses: Tiryoh/gha-jobid-action@v1
        with:
          github_token: ${{ steps.ggat.outputs.token }}
          job_name: '${{ inputs.CALLER_JOB }} / ${{ github.job }}'
          per_page: 100

      - name: Set up mutex for 'l10n' branch
        uses: ben-z/gh-action-mutex@v1.0.0-alpha.9
        with:
          branch: mutex/l10n
          repo-token: ${{ steps.ggat.outputs.token }}
          # Otherwise, the error message will show up:
          #   [8957344013-1714902604-928] Enqueuing to branch mutex/source, file mutex_queue
          #   [8957344013-1714902604-928] Adding ourself to the queue file mutex_queue
          #   remote: Write access to repository not granted.

      # required 'actions/checkout' with 'token: ${{ steps.ggat.outputs.token }}'
      - name: Add and Commit Changes
        id: acc
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './l10n'
          add: './${{ inputs.VERSION }}'
          pull: '--rebase --autostash'  # required 'actions/checkout' with 'fetch-depth: 0'
          author_name: docs-l10n[bot]
          author_email: 157310748+docs-l10n[bot]@users.noreply.github.com
          message: |
            po(${{ inputs.VERSION }}): Update po from Gettext

            Before: ${{ steps.po-before.outputs.VERSION_INFO }}
            After: ${{ steps.po-after.outputs.VERSION_INFO }}

            Created by GitHub Workflows:
            - File: ${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ github.workflow }}.yml
            - Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.gcji.outputs.job_id }}

      - name: Check Outputs of the Commit
        if: steps.acc.outputs.committed == 'true'
        shell: bash
        run: |
          echo "Commit's URL = ${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.acc.outputs.commit_long_sha }}"
          echo "Commit's SHA = ${{ steps.acc.outputs.commit_long_sha }}"
